### ISSUE TITLE
Display bank when importing file

### ISSUE THREAD

**Issue by tdeo** [bobar/tdfb#36]
At least give the choice

From: Gengen <>

**Comment by tdeo** [comment]
https://github.com/bobar/tdfb/commit/2bf43b88ef02084f41a5f175a49e330f98248f15 implements it in group log and file import.

**Comment by matthieu-gendreau** [comment]
:+1:

**Comment by matthieu-gendreau** [comment]
I am thinking maybe we can find a way to do import trigramme without opening a bank ?
Like adding a field: bank and passing it as an argument ?

**Comment by tdeo** [comment]
We can also implement that if it turns out useful.

**Comment by matthieu-gendreau** [comment]
Personnaly I find the process a bit confusing.
Especially when you start with the BôB bank, you can import your file, you validate and bim you just made the mistake of not selecting the correct bank because it was not explicit.
Maybe just a warning on top of the import "You are going to import this file to credit [BANK]. Please change if this is not correct" would just suffice?

**Comment by tdeo** [comment]
Sure

**Comment by matthieu-gendreau** [comment]
https://github.com/bobar/tdfb/commit/5f20d72ee8ef52dde0000d9f78b7806a9ad98a70
