### ISSUE TITLE
Run the TDB in production mode

### ISSUE THREAD

**Issue by matthieu-gendreau** [bobar/tdfb#41]
Or at least prevent to be stuck on a 500 page
Step to reproduce: try to import a bad xslx

**Comment by tdeo** [comment]
https://github.com/bobar/tdfb/commit/ff0faeacdf5f71cc5fbc56c28a42baffb958eeab should fix it (because now the forms are submitted with ajax even with a file attached). And also created an environment to have more flexibility in https://github.com/bobar/tdfb/commit/2eeb10055b924a389e02f9bb0d4e18ae411729ae
